### ISSUE TITLE
Add tests for forms after uninstalling

### ISSUE THREAD

**Issue by olga-nesterova** [ONLYOFFICE-QA/testing-site-onlyoffice#244]
Add tests for pages 
https://www.onlyoffice.com/desktop-uninstalled.aspx - saas portal
https://www.onlyoffice.com/account-canceled.aspx - personal 
https://www.onlyoffice.com/desktop-uninstalled.aspx - desktop

**Comment by JuliaBuvx** [comment]
implemented in #1922
