### ISSUE TITLE
Add to `[Site] Check Products` test check of Docs Enterprise, Docs Developer, Workspace Cloud and Workspace Enterprise pages

### ISSUE THREAD

**Issue by olga-nesterova** [ONLYOFFICE-QA/testing-site-onlyoffice#397]

**Comment by Qobiljonn** [comment]
These checks were added long time ago in several commits, namely:
Docs Enterprise in #792 
Docs Developer in #794 
Workspace Cloud in #829 
Workspace Enterprise in #833
