### ISSUE TITLE
Add tets for forms for site

### ISSUE THREAD

**Issue by amochalov85** [ONLYOFFICE-QA/testing-site-onlyoffice#624]
![изображение](https://user-images.githubusercontent.com/67409742/149619261-ed2f1a69-7c5d-423c-8b8f-28fb74d46f37.png)

https://github.com/ONLYOFFICE-QA/testing-site-onlyoffice/blob/master/spec/functional/about/site_about_contribute_spec.rb

**Comment by amochalov85** [comment]
Add after release oforms.teamlab.info

**Comment by ShockwaveNN** [comment]
Current version of oforms.onlyoffice.com has no <title> tag for html page

But oforoms.teamlab.info already has one, so we're waiting for release
