### ISSUE TITLE
Handle two links in Get Onlyoffice menu

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE-QA/testing-site-onlyoffice#907]
Workaround in https://github.com/ONLYOFFICE-QA/testing-site-onlyoffice/pull/906

Need proper check of both links

**Comment by Qobiljonn** [comment]
There are specs

**Comment by Qobiljonn** [comment]
There are 2 specs now in the folder spec/functional

site_onlyoffice_docs_enterprise_spec.rb  
and 
site_onlyoffice_docs_developer_spec.rb

which are used to check that these links are fully functional, and also the context of the pages.
